# US federal, state, and municipal agencies to recognize as organizations.
- United States Congress
- United States Senate
- United States House of Representatives
- Department of Transportation
- Department of Health and Human Services
- Department of Education
- Department of Housing and Urban Development
- Department of Homeland Security
- Department of Justice
- Department of the Treasury
- Department of Agriculture
- Department of the Interior
- Department of Energy
- Department of Labor
- Department of Commerce
- Department of Veterans Affairs
- Environmental Protection Agency
- Federal Emergency Management Agency
- Federal Transit Administration
- Government Accountability Office
- Office of Management and Budget
- National Governors Association
- National League of Cities
- United States Conference of Mayors
- Army Corps of Engineers
- Centers for Disease Control and Prevention
- Department of Public Health
- Department of Public Works
- Department of Finance
- Office of Emergency Management
- Planning and Zoning Commission
- Transportation Authority
